# Generated by Django 3.2.8 on 2022-01-12 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter valid mobile number.', regex='^[6-9]\\d{9}$')])),
                ('blood_group', models.IntegerField(choices=[(1, 'A+'), (2, 'B+'), (3, 'O+'), (4, 'AB+'), (5, 'A-'), (6, 'B-'), (7, 'O-'), (8, 'AB-')], default=1)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allergies', models.TextField(null=True)),
                ('Symptoms', models.TextField(null=True)),
                ('PregnancyStatus', models.BooleanField(default=False)),
                ('PreviousSurgery', models.TextField(null=True)),
                ('IsDiabetic', models.BooleanField(default=False)),
                ('InsurancePlanName', models.CharField(blank=True, max_length=10)),
                ('Status', models.IntegerField(choices=[(1, 'Recovered'), (2, 'Under Treatment')])),
                ('PatientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare.patient')),
            ],
        ),
    ]
