# Generated by Django 3.2.8 on 2022-01-14 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_alter_patient_registrationnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='createdDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='createdDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='updatedDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
