# Generated by Django 3.2.8 on 2022-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_auto_20220114_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodGroup',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
