# Generated by Django 2.2.12 on 2022-01-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_auto_20220114_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='insurancePlanNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='insurancePlanName',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
