# Generated by Django 3.2.8 on 2022-01-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_auto_20220114_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='insurancePlanNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='insurancePlanName',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='isDiabetic',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='pregnancyStatus',
            field=models.CharField(max_length=5),
        ),
    ]
